filebeat.inputs:
  - type: filestream
    id: system-logs
    enabled: true
    paths:
      - /var/log/default.log
    fields:
      kafka_topic: system-logs

# Kafka output
output.kafka:
  hosts: [ "kafka:29092" ]
  topic: '%{[fields.kafka_topic]}'
  codec.format:
    string: '%{[@timestamp]} %{[message]}'

# Monitoring endpoint
http.enabled: true
http.host: "0.0.0.0"
http.port: 5066
