global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'flink-jobmanager'
    metrics_path: '/jobmanager/metrics'
    static_configs:
      - targets: [ 'flink-jobmanager:8081' ]

  - job_name: 'flink-taskmanager'
    metrics_path: '/taskmanager/metrics'
    dns_sd_configs:
      - names:
          - 'tasks.flink-taskmanager'
        type: 'A'
        port: 8081

  - job_name: 'flink-metrics-exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'flink-taskmanager:9249'
          - 'flink-jobmanager:9249'

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]